# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: BaristaLabs, LLC - Brew your API
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Develop and surface microservices in SharePoint on-prem and store them as content. One Farm Deployment.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.baristalabs.com" # the base hostname & protocol for your site
twitter_username: baristalabs
instagram_username: baristalabs
github_username:  baristalabs
twitter_widget_id: 752903132238217217
discus_shortname: baristalabs

# Build settings
markdown: kramdown
highlighter: rouge

gems:
 - jekyll-paginate
 - jekyll-seo-tag
 - jekyll-sitemap

#Paginate Settings
paginate_path: "/blog/page:num/"
paginate: 5

timezone: America/New_York